### ISSUE TITLE
Installation and/or usage instructions?

### ISSUE THREAD

**Issue by NikiSchlifke** [AlexUg/sigrok#1]
@AlexUg 
Can you provide usage instructions for this patch?

I'll assume it goes this way:
1. Merge this project with the main sigrok sources
2. Apply the patches
3. Build it
4. Use the modified python script to download the firmware
5. Patch the firmware
6. Flash the firmware (how exactly)

**Comment by AlexUg** [comment]
Hi,
I afraid that these patches very old for appling to current sigrok sources. If i have time I will publish new patches ASAP. In addition, I found a bug related to the work of triggers.
But You may try:
1. Clone sigrok repository
2. Clone this repository
3. Use '0001-Add-Kingst-LA1010-support.patch' for patching libsigrok sources
4. Build sigrok
5. Use scirpt 'sigrok-fwextract-kingstvis.py' for extract firmwares
6. Copy firmwares to directory '~/.local/share/sigrok-firmware/'
7. Start pulseview....

If patches will not work then simplest way is coping folder 'kingst-la1010' as subdirectory to 'src/hardware' in libsigrok sources and making changes with 'Makefile.am.patch' and 'configure.ac.patch'.
And then build from step '4'.

**Comment by AlexUg** [comment]
I can provide DEB-packages for Ubuntu >=16.04. But I'm not sure if I can publish them.

**Comment by NikiSchlifke** [comment]
Thanks any pointers would be appreciated, I've got a kingst La1010 and just would like to use it. And not brick it. If you know the sigrok version you originally used I could go with it.

**Comment by AlexUg** [comment]
I were using latest commit from git-repository. But last build was done in march.

**Comment by depili** [comment]
The latest kingstvis archive doesn't seem to have any .dll:s that would match the provided sha256 sum, does anyone have a link to archive which can be used to extract the firmware?

**Comment by depili** [comment]
Checked both 3.0.5 (on the cd that came with la1010) and 3.0.9

**Comment by depili** [comment]
Apparently 2.0.9 has the required .dll: https://kingstvis.software.informer.com/2.0/ but finding the firmware on the 3.0 branch of the kingstvis would probably be a good idea.

**Comment by AlexUg** [comment]
Thanks for information.
Currently I'm not using analyzer often, therefore did not follow the software updates. I'll check the new .ddl and if there will no problem I will publish updated script.

**Comment by AlexUg** [comment]
> but finding the firmware on the 3.0 branch of the kingstvis would probably be a good idea.

After a cursory examination of new version revealed the following difficulties:
1. protocol for uploading Spartan firmware was changed therefore are needed a lot of changes in the code;
1. no firmwares were found in distribution (may be they're compressed or encrypted in some .dll, in which?).

**Comment by depili** [comment]
Then it is probably best to just document that you need the firmware from Kingstvis 2.0.9, as at least currently that version is still available on 3rd party sites and can be found with google.

**Comment by AlexUg** [comment]
You are right.
