### ISSUE TITLE
Error with firmware extract script

### ISSUE THREAD

**Issue by screwbreaker** [AlexUg/sigrok#3]
HI,
I got an error with the python script:

File "./sigrok-fwextract-kingstvis.py", line 83, in main
check_sum = (out_bytes[idx] + out_bytes[idx + 1] + out_bytes[idx + 2]) & 0xFF
TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by AlexUg** [comment]
I may be wrong but You run this script with Python 2.x. Try run with Python 3.x.

PS: There is KingstVIS for Linux and Mac (see http://www.qdkingst.com/en). Using a program from the manufacturer may be a better choice.

**Comment by screwbreaker** [comment]
You right! My bad!

I know about the KingstVIS, and it is not bad at all. But, I still prefer to have it working also with sigrok.

Thanks for the help.
