### ISSUE TITLE
upstreaming

### ISSUE THREAD

**Issue by diggit** [AlexUg/sigrok#4]
Hi, do you have any plans to merge your changes into upstream? Is there anything preventing this from happening (time/api compatibility/stability/licensing)?

**Comment by AlexUg** [comment]
I would be happy, that sources were been added to the upstream, but there are several reasons:

1. The maintainers of the upstream after checking my sources reported that it did not comply with the rules of code design. I tried to fix it, but the sources are still not accepted. I probably did something wrong, but there is no time to understand how to do it correctly. 

1. I use LA rarely and from time to time I find bugs in the sources, although it seems to work without errors for a year, but there is an obscure bug with the CLI (https://github.com/AlexUg/sigrok/issues/2) which is not clear how to fix.

1. A new version of software and firmware (with Linux support) is released. It is not clear yet how to get the firmware from the software and it seems that the protocol has changed a little and there is no time to deal with this at all.

PS: logic analyzer is just a rarely used assistant in my hobby, which I do only when I have free time.

**Comment by diggit** [comment]
Hi, thanks for clarification
1. do you have link to some PR or mailing list archive?

Looking though code, you've put decent amount of time to make it work.

I don't own this device and lot of other projects consume my time, but it would be nice to see such work merged.

**Comment by AlexUg** [comment]
Hi,

>     1. do you have link to some PR or mailing list archive?

No. I reported about my work in the IRC channel (if I'm not mistaken it called #sigrok), but I don't remember when it was.

**Comment by C47D** [comment]
Hey there, I just got a Kingst LA1010 and would love to see it supported in sigrok, did you worked on something else? I may have some free time and willing to make this accepted upstream.

**EDIT**
Have you used sigrok-cli on WSL? I don't have a Linux box right now.

**Comment by fastflo** [comment]
> Hey there, I just got a Kingst LA1010 and would love to see it supported in sigrok, did you worked on something else? I may have some free time and willing to make this accepted upstream.

hi all,
i managed to get LA2016 support pushed into sigrok. i already looked at this code here and it looks very promising. it should be easy enough to merge la1010 & la2016 code. i am currently preparing a new PR with some fixes (also targetted to windows users, but i can not test on windows - i don't have a windows box)
my fix-PR will be derived from https://github.com/fastflo/libsigrok/commits/kingst-la2016/no-packed
@C47D maybe you can try to merge @AlexUg's original code and this la2016? i would also be willing to help, but i can not help with windows build setup or usb tracing on windows...

**Comment by C47D** [comment]
Hi @fastflo 

I got a Windows box, I'm trying to setup a WSL instance so I can get libsigrok to build in there, just started a few minutes ago, so I'm in square one.

Maybe I should wait for your new PR to be merged into sigrok, on the meantime I can get familiar with your and @AlexUg work so we can merge the common LAx code.

> i would also be willing to help, but i can not help with windows build setup or usb tracing on windows...

I wasn't expected to get deep into USB sniffing, do you think Wireshark can help me out, or do I need any specialized tool for that?

What do you think?

**Comment by fastflo** [comment]
> I wasn't expected to get deep into USB sniffing, do you think Wireshark can help me out, or do I need any specialized tool for that?
> 
> What do you think?

wireshark works nicely on linux in combination with the linux-kernel-built-in usb-mon.
i don't know whether wireshark on windows can do the same.
i know there are other usb sniffers on windows - but its too long ago for me to remember a name.
i also don't know how good a WSL can emulate the linux api needed for libusb access (used by libsigrok). i would guess that there is at least some additional work needed to let windows know that a WSL process is allowed to talk to a usb device... but i dont know.

i would suggest you start to try to get @AlexUg 's code to work on your side (as it is directly targeted at your LA model). if you have a working build setup we can start merging necessary changes into the la2016 part of the sigrok codebase and you can test those on your side. 
a working usb sniffing setup might then help to find differences...

**Comment by AlexUg** [comment]
Hi all!
I can be helpful, but please treat with understanding to the fact that I have an acute shortage of free time.

**Comment by diggit** [comment]
hi @AlexUg, did you ma age to get it into upstream? I did not find any mention about LA1010 there in kingst driver.

**Comment by AlexUg** [comment]
There is info that latest libsigrok does support LA1010, but I does not testing it yet.
