### ISSUE TITLE
Availability of LA1010.dll (or the older kingst software to extract the FW)

### ISSUE THREAD

**Issue by sambartle** [AlexUg/sigrok#5]
Not an issue with the code at all but does anyone have a location to download either the LA1010.dll file directly? Or a URL for the old software?

The Kingst site appears to only contain newer software versions, which is preventing me making much progress with getting this to work with Sigrok.

**Comment by AlexUg** [comment]
Hi,
this is installation exe-file of version 2.1.0:
[kingst.zip](https://github.com/AlexUg/sigrok/files/4582558/kingst.zip)

**Comment by sambartle** [comment]
Perfect, thanks AlexUg

Regards,
Sam Bartle

**Comment by AlexUg** [comment]
At this time there is available extracting firmware from new version of Kingst software for GNU/Linux platform.
