### ISSUE TITLE
Reopen Issue Request

### ISSUE THREAD

**Issue by Tyrn** [AlexUg/sigrok#8]
Please make visible the *Trying to follow the steps* issue. There is important info there.

**Comment by AlexUg** [comment]
You can see this request in 'Closed' tab.
![image](https://user-images.githubusercontent.com/8567016/134628869-fc63b26a-7bdd-45cd-ad2a-c607e2fb45cb.png)

**Comment by Tyrn** [comment]
Thanks! I found it. there are problems with the library updated to 3.5 kingst. It would be logical to reopen the old and still relevant issue; if you don't think so, I'll open a new one.
