### ISSUE TITLE
Trying to follow the steps - 2

### ISSUE THREAD

**Issue by Tyrn** [AlexUg/sigrok#9]
I tried to build it according to my experience: I put the directory `kingst-la1010` into the `src/hardware` directory of the `libsigrok` sources. Alongside `kingst-la2016`, by the way. Do I have to remove the latter because the two of them are in conflict, as the README says? I guess the patches are no longer needed.

The build is successful; the run is not. The app shows briefly, it starts and ends with "scanning devices...". I could not have advanced even this far if it had not been for my previous experience. The step-by-step build instruction is still not quite clear.

**Comment by AlexUg** [comment]
I'm sorry. There was the mistake in README. I had prepared fork of original repo -- https://github.com/AlexUg/libsigrok -- for support LA-1010.
